package GUI;

import javax.swing.JFrame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import static risk.game.RiskGame.currentPlayer;
import static risk.game.RiskGame.players;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ahmed
 */
public class EgyptFrame extends javax.swing.JFrame implements GameFrame {

    /**
     * Creates new form GameFrame
     */
    public EgyptFrame() {
        initComponents();
    }
    
    @Override
    public void start()
    {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public static final int[][] egyptNEIGHBORS = {{},
                                             {4,14},                    //01
                                             {17,22,21},                //02
                                             {15,17,22,24},             //03
                                             {1,10,11,13,14,16},        //04
                                             {6,9,11,15,22},            //05
                                             {5,11,20,22,23,26},        //06
                                             {8,10,13,20,23},           //07
                                             {7},                       //08
                                             {5,11},                    //09
                                             {4,7,13,16},               //10
                                             {4,5,6,9,14,15,16,17,20},  //11
                                             {18,19,23,26},             //12
                                             {4,7,10},                  //13
                                             {1,4,11,17},               //14
                                             {3,5,11,17,22},            //15
                                             {4,10,11,20},              //16
                                             {2,3,11,14,15,21,24},      //17
                                             {12,19,25,26},             //18
                                             {12,18},                   //19
                                             {6,7,11,16,23},            //20
                                             {2,17,22,24,27},           //21
                                             {2,3,5,6,15,21,24,26},     //22
                                             {6,7,12,20,26},         //23
                                             {3,17,21,22},              //24
                                             {18,26},                   //25
                                             {6,12,18,22,23,25},        //26
                                             {21}};                     //27 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g)
            {
                ImageIcon imageIcon = new ImageIcon("egyptmap.png");
                Image image = imageIcon.getImage();
                g.drawImage(image, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jButton1 = new GUI.TerritoryButton(14);
        jButton2 = new GUI.TerritoryButton(17);
        jButton3 = new GUI.TerritoryButton(11);
        jButton4 = new GUI.TerritoryButton(15);
        jButton5 = new GUI.TerritoryButton(5);
        jButton6 = new GUI.TerritoryButton(9);
        jButton7 = new GUI.TerritoryButton(4);
        jButton8 = new GUI.TerritoryButton(1);
        jButton9 = new GUI.TerritoryButton(2);
        jButton10 = new GUI.TerritoryButton(13);
        jButton11 = new GUI.TerritoryButton(10);
        jButton12 = new GUI.TerritoryButton(16);
        jButton13 = new GUI.TerritoryButton(20);
        jButton14 = new GUI.TerritoryButton(8);
        jButton15 = new GUI.TerritoryButton(19);
        jButton16 = new GUI.TerritoryButton(26);
        jButton17 = new GUI.TerritoryButton(6);
        jButton18 = new GUI.TerritoryButton(7);
        jButton19 = new GUI.TerritoryButton(23);
        jButton20 = new GUI.TerritoryButton(12);
        jButton21 = new GUI.TerritoryButton(18);
        jButton22 = new GUI.TerritoryButton(25);
        jButton23 = new GUI.TerritoryButton(3);
        jButton24 = new GUI.TerritoryButton(24);
        jButton25 = new GUI.TerritoryButton(27);
        jButton26 = new GUI.TerritoryButton(22);
        jButton27 = new GUI.TerritoryButton(21);
        statePanel = new javax.swing.JPanel();
        endAttackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        playerNameLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        additionalArmiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(906, 806));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 35, 35));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 37, 37));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 280, 30, 30));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 310, 35, 35));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 255, 22, 22));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 231, 25, 25));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 115, 25, 25));
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 101, 21, 21));
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 710, 27, 27));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 60, 27, 27));
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 96, 24, 24));
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 122, 22, 22));
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 145, 22, 22));
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 22, 24, 24));
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 25, 31, 31));
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 160, 33, 33));
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 195, 26, 26));
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 82, 24, 24));
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 106, 26, 26));
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 110, 31, 31));
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 125, 33, 33));
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 254, 34, 34));
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 388, 33, 33));
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 450, 33, 33));
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 33, 33));
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 592, 33, 33));
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 33, 33));

        statePanel.setBackground(new java.awt.Color(31, 96, 155));
        statePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endAttackButton.setBackground(new java.awt.Color(255, 255, 255));
        endAttackButton.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        endAttackButton.setText("End Attack");
        endAttackButton.setEnabled(false);
        endAttackButton.setFocusPainted(false);
        endAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endAttackButtonActionPerformed(evt);
            }
        });
        statePanel.add(endAttackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 130, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerNameLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        playerNameLabel.setText("Aggresive");
        playerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        playerNameLabel.setPreferredSize(new java.awt.Dimension(196, 50));
        jPanel2.add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, 122, 40));
        jPanel2.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 66, 65));

        statePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 210, 66));

        additionalArmiesLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        additionalArmiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        additionalArmiesLabel.setText("random initalize");
        statePanel.add(additionalArmiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 130, 27));

        jPanel1.add(statePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 1006, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 906));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endAttackButtonActionPerformed
        players[currentPlayer].clickedEndAttack();
    }//GEN-LAST:event_endAttackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalArmiesLabel;
    private javax.swing.JButton endAttackButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JPanel statePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public JLabel getAdditionalArmiesLabel() {
        return additionalArmiesLabel;
    }

    @Override
    public JButton getEndAttackButton() {
        return endAttackButton;
    }

    @Override
    public JLabel getIconLabel() {
        return iconLabel;
    }

    @Override
    public JLabel getPlayerNameLabel() {
        return playerNameLabel;
    }
}
