/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.EgyptFrame.egyptNEIGHBORS;
import static GUI.USFrame.USNeighbors;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static risk.game.RiskGame.gameFrame;
import static risk.game.RiskGame.noOfTerritories;
import static risk.game.RiskGame.NEIGHBORS;

/**
 *
 * @author Ahmed
 */
public class MapFrame extends javax.swing.JFrame {

    /**
     * Creates new form MapFrame
     */
    public MapFrame() {
        initComponents();
    }

    
    public void start()
    {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton(){

            @Override
            public void paintComponent(Graphics g)
            {
                ImageIcon imageIcon = new ImageIcon("USmap.png");
                Image image = imageIcon.getImage();
                g.drawImage(image, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jButton2 = new javax.swing.JButton(){

            @Override
            public void paintComponent(Graphics g)
            {
                ImageIcon imageIcon = new ImageIcon("egyptmap.png");
                Image image = imageIcon.getImage();
                g.drawImage(image, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 103, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 183, 81));
        titleLabel.setText("Select Map");
        jPanel4.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 260, 50));

        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 270, 270));

        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 270, 270));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("US Map");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 200, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Egypt Map");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 200, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gameFrame = new EgyptFrame();
        noOfTerritories = 27;
        NEIGHBORS = egyptNEIGHBORS;
        this.setVisible(false);
        startFrame sf = new startFrame();
        sf.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gameFrame = new USFrame();
        noOfTerritories = 50;
        NEIGHBORS = USNeighbors;
        this.setVisible(false);
        startFrame sf = new startFrame();
        sf.start();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
