/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Player.AStarPlayer;
import static Player.AStarPlayer.AStarIcon;
import Player.RealTimePlayer;
import static Player.AggressivePlayer.aggresiveIcon;
import static Player.GreedyPlayer.greedyIcon;
import static Player.MinimaxPlayer.MinMaxIcon;
import static Player.PacifistPlayer.pacifistIcon;
import static Player.PassivePlayer.passiveIcon;
import Player.Player;
import static Player.RealTimePlayer.AStarSearchIcon;
import Player.AggressivePlayer;
import Player.GreedyPlayer;
import Player.MinimaxPlayer;
import Player.PacifistPlayer;
import Player.PassivePlayer;
import javax.swing.JFrame;
import static risk.game.RiskGame.TIMER;
import static risk.game.RiskGame.changePlayer;
import static risk.game.RiskGame.currentPlayer;
import static risk.game.RiskGame.gameFrame;
import static risk.game.RiskGame.players;
import static risk.game.RiskGame.playersColor;
/**
 *
 * @author Ahmed
 */
public class PlayerFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectFrame
     */
    public PlayerFrame() {
        initComponents();
        this.aggressiveBtn.setIcon(aggresiveIcon);
        this.AStarBtn.setIcon(AStarIcon);
        this.GreedyBtn.setIcon(greedyIcon);
        this.MinmaxBtn.setIcon(MinMaxIcon);
        this.realTimeBtn.setIcon(AStarSearchIcon);
        this.passiveBtn.setIcon(passiveIcon);
        this.pacifistBtn.setIcon(pacifistIcon);
    }

    public void start(String title)
    {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.titleLabel.setText(title);
    }
    
    private void addPlayer(Player player)
    {
        players[currentPlayer] = player;
        changePlayer();
        if(currentPlayer == 0)
        {
            this.setVisible(false);
            gameFrame.start();
            gameFrame.getPlayerNameLabel().setText(players[currentPlayer].getName());
            gameFrame.getPlayerNameLabel().setForeground(players[currentPlayer].getColor());
            gameFrame.getIconLabel().setIcon(players[currentPlayer].Icon());
            TIMER.start();
        }
        this.titleLabel.setText(" Choose   Player2");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        passiveBtn = new javax.swing.JButton();
        aggressiveBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        pacifistBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        AStarBtn = new javax.swing.JButton();
        realTimeBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        MinmaxBtn = new javax.swing.JButton();
        GreedyBtn = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 103, 103));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel1.setText("Stupid robot");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        passiveBtn.setBackground(new java.awt.Color(255, 255, 255));
        passiveBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        passiveBtn.setForeground(new java.awt.Color(255, 204, 102));
        passiveBtn.setText("Passive");
        passiveBtn.setFocusPainted(false);
        passiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passiveBtnActionPerformed(evt);
            }
        });
        jPanel6.add(passiveBtn);

        aggressiveBtn.setBackground(new java.awt.Color(255, 255, 255));
        aggressiveBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        aggressiveBtn.setForeground(new java.awt.Color(255, 204, 102));
        aggressiveBtn.setText("Aggressive");
        aggressiveBtn.setFocusPainted(false);
        aggressiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggressiveBtnActionPerformed(evt);
            }
        });
        jPanel6.add(aggressiveBtn);

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 90));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        pacifistBtn.setBackground(new java.awt.Color(255, 255, 255));
        pacifistBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        pacifistBtn.setForeground(new java.awt.Color(255, 204, 102));
        pacifistBtn.setText("Pacifist");
        pacifistBtn.setFocusPainted(false);
        pacifistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacifistBtnActionPerformed(evt);
            }
        });
        jPanel7.add(pacifistBtn);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 180));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel2.setText("Intelligent robot");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        AStarBtn.setBackground(new java.awt.Color(255, 255, 255));
        AStarBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AStarBtn.setForeground(new java.awt.Color(255, 204, 102));
        AStarBtn.setText("A*");
        AStarBtn.setFocusPainted(false);
        AStarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AStarBtnActionPerformed(evt);
            }
        });
        jPanel9.add(AStarBtn);

        realTimeBtn.setBackground(new java.awt.Color(255, 255, 255));
        realTimeBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        realTimeBtn.setForeground(new java.awt.Color(255, 204, 102));
        realTimeBtn.setText("realtime");
        realTimeBtn.setFocusPainted(false);
        realTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realTimeBtnActionPerformed(evt);
            }
        });
        jPanel9.add(realTimeBtn);

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 90));

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        MinmaxBtn.setBackground(new java.awt.Color(255, 255, 255));
        MinmaxBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        MinmaxBtn.setForeground(new java.awt.Color(255, 204, 102));
        MinmaxBtn.setText("Minimax");
        MinmaxBtn.setFocusPainted(false);
        MinmaxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinmaxBtnActionPerformed(evt);
            }
        });
        jPanel10.add(MinmaxBtn);

        GreedyBtn.setBackground(new java.awt.Color(255, 255, 255));
        GreedyBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        GreedyBtn.setForeground(new java.awt.Color(255, 204, 102));
        GreedyBtn.setText("Greedy");
        GreedyBtn.setFocusPainted(false);
        GreedyBtn.setIconTextGap(8);
        GreedyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreedyBtnActionPerformed(evt);
            }
        });
        jPanel10.add(GreedyBtn);

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 480, 90));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 480, 180));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 500, 500));

        titleLabel.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 183, 81));
        titleLabel.setText("Choose   Opponent");
        jPanel2.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 450, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passiveBtnActionPerformed
        addPlayer(new PassivePlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_passiveBtnActionPerformed

    private void aggressiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggressiveBtnActionPerformed
        addPlayer(new AggressivePlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_aggressiveBtnActionPerformed

    private void pacifistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacifistBtnActionPerformed
        addPlayer(new PacifistPlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_pacifistBtnActionPerformed

    private void AStarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AStarBtnActionPerformed
        addPlayer(new AStarPlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_AStarBtnActionPerformed

    private void realTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realTimeBtnActionPerformed
        addPlayer(new RealTimePlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_realTimeBtnActionPerformed

    private void MinmaxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinmaxBtnActionPerformed
        addPlayer(new MinimaxPlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_MinmaxBtnActionPerformed

    private void GreedyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreedyBtnActionPerformed
        addPlayer(new GreedyPlayer(playersColor[currentPlayer]));
    }//GEN-LAST:event_GreedyBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AStarBtn;
    private javax.swing.JButton GreedyBtn;
    private javax.swing.JButton MinmaxBtn;
    private javax.swing.JButton aggressiveBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton pacifistBtn;
    private javax.swing.JButton passiveBtn;
    private javax.swing.JButton realTimeBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
