package GUI;

import javax.swing.JFrame;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import static risk.game.RiskGame.currentPlayer;
import static risk.game.RiskGame.players;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ahmed
 */
public class USFrame extends javax.swing.JFrame implements GameFrame {

    /**
     * Creates new form GameFrame
     */
    
    public static int[][] USNeighbors = {{},
    {2, 5, 50},                         //01
    {1, 3, 4, 5},                       //02
    {2, 4, 9, 49},                      //03
    {2, 3, 5, 8, 9},                    //04
    {1, 2, 4, 6, 7, 8},                 //05
    {5, 7, 16, 17},                     //06
    {5, 6, 8, 10, 15, 16},              //07
    {4, 5, 7, 9,10,11},                 //08
    {3, 4, 8, 10, 11, 49},              //09
    {7, 8, 9, 11, 13, 14, 15},          //10
    {8, 9, 10, 12, 13},                 //11
    {11, 13, 21, 22},                   //12
    {10, 11, 12, 14, 20, 21},           //13
    {10, 13, 15, 20},                   //14
    {7, 10, 14, 16, 19, 20},            //15
    {6, 7, 15, 17, 18, 19},             //16
    {6, 16, 18},                        //17
    {16, 17, 19, 34},                   //18
    {15, 16, 18, 20, 33, 34},           //19
    {13, 14, 15, 19, 21, 31, 32, 33},   //20
    {12, 13, 20, 22, 23, 31},           //21
    {12, 21, 23},                       //22
    {21, 22, 24, 31},                   //23
    {23, 25, 26, 31},                   //24
    {24, 26},                           //25
    {24, 25, 27, 28, 31},               //26
    {26, 28},                           //27
    {26, 27, 29, 31},                   //28
    {28, 30, 31, 32, 48},               //29
    {29, 32, 37, 38, 48},               //30
    {20, 21, 23, 24, 26, 28, 29, 32},   //31
    {20, 29, 30, 31, 33, 35, 37},       //32
    {19, 20, 32, 34, 35, 36},           //33
    {18, 19, 33, 36},                   //34
    {32, 33, 36, 37},                   //35
    {33, 34, 35, 37},                   //36
    {30, 32, 35, 36, 38},               //37
    {30, 37, 39, 46, 47, 48},           //38
    {38, 40, 43, 45, 46},               //39
    {39, 41, 43},                       //40
    {40, 42, 43},                       //41
    {41},                               //42
    {39, 40, 41, 44, 45},               //43
    {43, 45},                           //44
    {39, 43, 44, 46},                   //45
    {38, 39, 45, 47},                   //46
    {38, 46, 48},                       //47
    {29, 30, 38, 47},                   //48
    {3, 9},                             //49
    {1}                                 //50

    };
    
    public USFrame() {
        initComponents();
    }
    
    @Override
    public void start()
    {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){

            @Override
            public void paintComponent(Graphics g)
            {
                ImageIcon imageIcon = new ImageIcon("USmap.png");
                Image image = imageIcon.getImage();
                g.drawImage(image, 0, 0, this.getSize().width, this.getSize().height,this);
            }

        };
        jButton8 = new GUI.TerritoryButton(25);
        jButton9 = new GUI.TerritoryButton(50);
        jButton10 = new GUI.TerritoryButton(7);
        jButton11 = new GUI.TerritoryButton(11);
        jButton12 = new GUI.TerritoryButton(41);
        jButton13 = new GUI.TerritoryButton(17);
        jButton14 = new GUI.TerritoryButton(42);
        jButton15 = new GUI.TerritoryButton(43);
        jButton16 = new GUI.TerritoryButton(44);
        jButton17 = new GUI.TerritoryButton(45);
        jButton18 = new GUI.TerritoryButton(46);
        jButton19 = new GUI.TerritoryButton(47);
        jButton20 = new GUI.TerritoryButton(48);
        jButton21 = new GUI.TerritoryButton(6);
        jButton22 = new GUI.TerritoryButton(1);
        jButton23 = new GUI.TerritoryButton(2);
        jButton24 = new GUI.TerritoryButton(29);
        jButton25 = new GUI.TerritoryButton(4);
        jButton26 = new GUI.TerritoryButton(49);
        jButton27 = new GUI.TerritoryButton(3);
        jButton28 = new GUI.TerritoryButton(40);
        jButton29 = new GUI.TerritoryButton(5);
        jButton30 = new GUI.TerritoryButton(8);
        jButton31 = new GUI.TerritoryButton(9);
        jButton32 = new GUI.TerritoryButton(10);
        jButton33 = new GUI.TerritoryButton(16);
        jButton34 = new GUI.TerritoryButton(18);
        jButton35 = new GUI.TerritoryButton(34);
        jButton36 = new GUI.TerritoryButton(19);
        jButton37 = new GUI.TerritoryButton(15);
        jButton38 = new GUI.TerritoryButton(14);
        jButton39 = new GUI.TerritoryButton(13);
        jButton40 = new GUI.TerritoryButton(12);
        jButton42 = new GUI.TerritoryButton(22);
        jButton43 = new GUI.TerritoryButton(21);
        jButton44 = new GUI.TerritoryButton(20);
        jButton45 = new GUI.TerritoryButton(33);
        jButton46 = new GUI.TerritoryButton(35);
        jButton47 = new GUI.TerritoryButton(36);
        jButton48 = new GUI.TerritoryButton(39);
        jButton49 = new GUI.TerritoryButton(38);
        jButton50 = new GUI.TerritoryButton(37);
        jButton51 = new GUI.TerritoryButton(30);
        jButton52 = new GUI.TerritoryButton(32);
        jButton53 = new GUI.TerritoryButton(31);
        jButton54 = new GUI.TerritoryButton(23);
        jButton55 = new GUI.TerritoryButton(24);
        jButton56 = new GUI.TerritoryButton(26);
        jButton57 = new GUI.TerritoryButton(27);
        jButton58 = new GUI.TerritoryButton(28);
        statePanel = new javax.swing.JPanel();
        endAttackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        playerNameLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        additionalArmiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(906, 806));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 730, 31, 31));
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 70, 30, 30));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 32, 32));
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 590, 30, 30));
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 250, 31, 31));
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 280, 35, 35));
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 31, 31));
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 334, 31, 31));
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 380, 32, 32));
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 410, 32, 32));
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 430, 31, 31));
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 461, 30, 30));
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 505, 31, 31));
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 40, 40));
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 30, 30));
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 305, 30, 30));
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 490, 35, 35));
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 30, 30));
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 36, 36));
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 474, 30, 30));
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 270, 31, 31));
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 30, 30));
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 30, 30));
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 30, 30));
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 470, 35, 35));
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 30, 30));
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 30, 30));
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 30, 30));
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 35, 35));
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 35, 35));
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 35, 35));
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 579, 34, 32));
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 40, 40));
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 35, 35));
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, 35, 35));
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 510, 35, 35));
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 455, 35, 35));
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 460, 30, 30));
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 30, 30));
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 35, 35));
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 35, 35));
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 35, 35));
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 490, 30, 30));
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 510, 33, 33));
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 560, 33, 33));
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 35, 35));
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 32, 32));
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 35, 35));
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 587, 35, 35));
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 550, 35, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 830));

        statePanel.setBackground(new java.awt.Color(31, 96, 155));
        statePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endAttackButton.setBackground(new java.awt.Color(255, 255, 255));
        endAttackButton.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        endAttackButton.setText("End Attack");
        endAttackButton.setEnabled(false);
        endAttackButton.setFocusPainted(false);
        endAttackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endAttackButtonActionPerformed(evt);
            }
        });
        statePanel.add(endAttackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 130, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerNameLabel.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        playerNameLabel.setText("Aggresive");
        playerNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        playerNameLabel.setPreferredSize(new java.awt.Dimension(196, 50));
        jPanel2.add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, 122, 40));
        jPanel2.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 66, 65));

        statePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 210, 66));

        additionalArmiesLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        additionalArmiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        additionalArmiesLabel.setText("random initalize");
        statePanel.add(additionalArmiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 130, 27));

        getContentPane().add(statePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 1006, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endAttackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endAttackButtonActionPerformed
        players[currentPlayer].clickedEndAttack();
    }//GEN-LAST:event_endAttackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalArmiesLabel;
    private javax.swing.JButton endAttackButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JPanel statePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public JLabel getAdditionalArmiesLabel() {
        return additionalArmiesLabel;
    }

    @Override
    public JButton getEndAttackButton() {
        return endAttackButton;
    }

    @Override
    public JLabel getIconLabel() {
        return iconLabel;
    }

    @Override
    public JLabel getPlayerNameLabel() {
        return playerNameLabel;
    }
}
